# Generated by Django 4.1 on 2022-09-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_place', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='menu',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Votes'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='day',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_text',
            field=models.TextField(max_length=200),
        ),
    ]
