# Generated by Django 4.1 on 2022-09-23 11:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_place', '0002_remove_employee_restaurant_menu_votes_alter_menu_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='lunch_time',
            field=models.TimeField(default=datetime.time(13, 0), unique=True, verbose_name='Lunch time'),
        ),
        migrations.AddField(
            model_name='employee',
            name='selected_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lunch_place.menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch_place.restaurant', unique_for_date='day'),
        ),
    ]
